export const I18N = {
    pt: {
        title: "BTC Valuation Score (Checklist → Score)",
        subtitle: "Preencha os 4 itens do checklist e veja o score (0–100) + ação sugerida. Sem previsão, sem trade.",
        checklist: "Checklist",
        result: "Resultado",
        thermometer: "Termômetro",
        breakdown: "Detalhamento (contribuição no score)",
        quickRules: "Regras rápidas",
        reset: "Resetar",
        adjustWeights: "Ajustar pesos (opcional)",
        adjustWeightsHint: "Se mudar os pesos, o app normaliza automaticamente para somar 100%.",
        normalizedWeights: "Pesos normalizados:",
        suggestedAction: "Ação sugerida:",
        footer: "Observação: isso é um framework de valuation/risco (não previsão). Use como disciplina de aporte e redução gradual.",
        copiedAddress: 'Endereço copiado!',
        pillars: {
            mvrv: "1) MVRV Z-Score (valor justo econômico)",
            mayer: "2) Mayer Multiple (preço vs tendência)",
            s2f: "3) Stock-to-Flow (escassez, contexto macro)",
            fearGreed: "4) Fear & Greed (psicologia)",
        },
        bands: {
            undervaluedStrong: "Forte subvalorização",
            fair: "Valor justo / atrativo",
            neutral: "Neutro",
            stretched: "Esticado",
            euphoria: "Euforia",
        },
        actions: {
            aggressive: "Aporte agressivo (reforçar aportes)",
            normal: "Aporte normal",
            minimal: "Aporte mínimo / normal (conservador)",
            caution: "Cautela (reduzir ritmo de aporte)",
            reduce: "Considerar redução parcial (5–15%)",
        },
        options: {
            mvrv: {
                lt0: "Z < 0 (subvalorização extrema)",
                "0_1": "0 ≤ Z < 1 (barato)",
                "1_2": "1 ≤ Z < 2 (ok/atrativo)",
                "2_3": "2 ≤ Z < 3 (justo)",
                "3_5": "3 ≤ Z < 5 (caro)",
                gt5: "Z ≥ 5 (euforia)",
            },
            mayer: {
                lt0_8: "Mayer < 0,8 (muito descontado)",
                "0_8_1_3": "0,8–1,3 (saudável)",
                "1_3_2_0": "1,3–2,0 (esticado)",
                "2_0_2_4": "2,0–2,4 (quase euforia)",
                gt2_4: "≥ 2,4 (euforia)",
            },
            s2f: {
                far_below: "Muito abaixo da curva S2F",
                below: "Abaixo da curva S2F",
                near: "Próximo da curva S2F",
                above: "Acima da curva S2F",
                far_above: "Muito acima da curva S2F",
            },
            fearGreed: {
                lt20: "< 20 (medo extremo)",
                "20_40": "20–40 (medo)",
                "40_60": "40–60 (neutro)",
                "60_75": "60–75 (ganância)",
                gt75: "> 75 (ganância extrema)",
            },
        },
        weights: {
            mvrv: "Peso MVRV",
            mayer: "Peso Mayer",
            s2f: "Peso S2F",
            fearGreed: "Peso Fear & Greed",
        },
    },

    en: {
        title: "BTC Valuation Score (Checklist → Score)",
        subtitle: "Fill the 4 checklist items to get a score (0–100) + suggested action. No predictions, no trading.",
        checklist: "Checklist",
        result: "Result",
        thermometer: "Thermometer",
        breakdown: "Breakdown (score contribution)",
        quickRules: "Quick rules",
        reset: "Reset",
        adjustWeights: "Adjust weights (optional)",
        adjustWeightsHint: "If you change weights, the app normalizes them to sum to 100%.",
        normalizedWeights: "Normalized weights:",
        suggestedAction: "Suggested action:",
        footer: "Note: this is a valuation/risk framework (not a prediction). Use it to guide gradual buying and trimming.",
        copiedAddress: 'Address copied!',
        pillars: {
            mvrv: "1) MVRV Z-Score (economic fair value)",
            mayer: "2) Mayer Multiple (price vs trend)",
            s2f: "3) Stock-to-Flow (scarcity, macro context)",
            fearGreed: "4) Fear & Greed (psychology)",
        },
        bands: {
            undervaluedStrong: "Strong undervaluation",
            fair: "Fair / attractive",
            neutral: "Neutral",
            stretched: "Stretched",
            euphoria: "Euphoria",
        },
        actions: {
            aggressive: "Buy aggressively (increase DCA)",
            normal: "Normal DCA",
            minimal: "Minimal / conservative DCA",
            caution: "Be cautious (slow down buying)",
            reduce: "Consider partial trimming (5–15%)",
        },
        options: {
            mvrv: {
                lt0: "Z < 0 (extreme undervaluation)",
                "0_1": "0 ≤ Z < 1 (cheap)",
                "1_2": "1 ≤ Z < 2 (ok/attractive)",
                "2_3": "2 ≤ Z < 3 (fair)",
                "3_5": "3 ≤ Z < 5 (expensive)",
                gt5: "Z ≥ 5 (euphoria)",
            },
            mayer: {
                lt0_8: "Mayer < 0.8 (deep discount)",
                "0_8_1_3": "0.8–1.3 (healthy)",
                "1_3_2_0": "1.3–2.0 (stretched)",
                "2_0_2_4": "2.0–2.4 (near euphoria)",
                gt2_4: "≥ 2.4 (euphoria)",
            },
            s2f: {
                far_below: "Far below the S2F curve",
                below: "Below the S2F curve",
                near: "Near the S2F curve",
                above: "Above the S2F curve",
                far_above: "Far above the S2F curve",
            },
            fearGreed: {
                lt20: "< 20 (extreme fear)",
                "20_40": "20–40 (fear)",
                "40_60": "40–60 (neutral)",
                "60_75": "60–75 (greed)",
                gt75: "> 75 (extreme greed)",
            },
        },
        weights: {
            mvrv: "MVRV weight",
            mayer: "Mayer weight",
            s2f: "S2F weight",
            fearGreed: "Fear & Greed weight",
        },
    },

    es: {
        title: "BTC Valuation Score (Checklist → Score)",
        subtitle: "Completa los 4 puntos del checklist y obtén un score (0–100) + acción sugerida. Sin predicción, sin trading.",
        checklist: "Checklist",
        result: "Resultado",
        thermometer: "Termómetro",
        breakdown: "Detalle (contribución al score)",
        quickRules: "Reglas rápidas",
        reset: "Restablecer",
        adjustWeights: "Ajustar pesos (opcional)",
        adjustWeightsHint: "Si cambias los pesos, la app los normaliza para sumar 100%.",
        normalizedWeights: "Pesos normalizados:",
        suggestedAction: "Acción sugerida:",
        footer: "Nota: esto es un marco de valoración/riesgo (no una predicción). Úsalo para compras y reducciones graduales.",
        copiedAddress: '¡Dirección copiada!',
        pillars: {
            mvrv: "1) MVRV Z-Score (valor justo económico)",
            mayer: "2) Mayer Multiple (precio vs tendencia)",
            s2f: "3) Stock-to-Flow (escasez, contexto macro)",
            fearGreed: "4) Fear & Greed (psicología)",
        },
        bands: {
            undervaluedStrong: "Fuerte infravaloración",
            fair: "Justo / atractivo",
            neutral: "Neutral",
            stretched: "Estirado",
            euphoria: "Euforia",
        },
        actions: {
            aggressive: "Compra agresiva (aumentar aportes)",
            normal: "Aporte normal",
            minimal: "Aporte mínimo / conservador",
            caution: "Precaución (bajar ritmo de compra)",
            reduce: "Considerar reducción parcial (5–15%)",
        },
        options: {
            mvrv: {
                lt0: "Z < 0 (infravaloración extrema)",
                "0_1": "0 ≤ Z < 1 (barato)",
                "1_2": "1 ≤ Z < 2 (ok/atractivo)",
                "2_3": "2 ≤ Z < 3 (justo)",
                "3_5": "3 ≤ Z < 5 (caro)",
                gt5: "Z ≥ 5 (euforia)",
            },
            mayer: {
                lt0_8: "Mayer < 0,8 (muy descontado)",
                "0_8_1_3": "0,8–1,3 (saludable)",
                "1_3_2_0": "1,3–2,0 (estirado)",
                "2_0_2_4": "2,0–2,4 (casi euforia)",
                gt2_4: "≥ 2,4 (euforia)",
            },
            s2f: {
                far_below: "Muy por debajo de la curva S2F",
                below: "Por debajo de la curva S2F",
                near: "Cerca de la curva S2F",
                above: "Por encima de la curva S2F",
                far_above: "Muy por encima de la curva S2F",
            },
            fearGreed: {
                lt20: "< 20 (miedo extremo)",
                "20_40": "20–40 (miedo)",
                "40_60": "40–60 (neutral)",
                "60_75": "60–75 (codicia)",
                gt75: "> 75 (codicia extrema)",
            },
        },
        weights: {
            mvrv: "Peso MVRV",
            mayer: "Peso Mayer",
            s2f: "Peso S2F",
            fearGreed: "Peso Fear & Greed",
        },
    },
} as const;
